# Trading Bot Configuration
api:
  okx:
    # Set these in environment variables or .env file
    api_key: "${OKX_API_KEY}"
    api_secret: "${OKX_API_SECRET}"
    passphrase: "${OKX_PASSPHRASE}"
    sandbox: true  # Демо-режим OKX
    
trading:
  symbols: 
    - "BTC-USDT"
    - "ETH-USDT"
    - "SOL-USDT"
  base_currency: "USDT"
  
# Risk Management
risk:
  max_position_size_percent: 5.0  # Max 5% of balance per position
  max_daily_loss_percent: 10.0    # Stop trading if daily loss exceeds 10%
  risk_per_trade_percent: 1.0     # Risk 1% per trade
  max_open_positions: 3           # Maximum concurrent positions

# Scalping Strategy
scalping:
  enabled: true
  symbols: ["BTC-USDT", "ETH-USDT", "SOL-USDT"]
  timeframe: "1m"
  
  # PHASE 1: Multi-Timeframe Confirmation (MTF)
  multi_timeframe_enabled: true  # Включим после тестов
  multi_timeframe:
    confirmation_timeframe: "5m"  # Таймфрейм для подтверждения
    score_bonus: 2                # Бонус к score при подтверждении
    block_opposite: true          # Блокировать противоположные сигналы
    ema_fast_period: 8            # Период быстрой EMA
    ema_slow_period: 21           # Период медленной EMA
    cache_ttl_seconds: 30         # Кэш свечей (секунды)
  
  # PHASE 1: Correlation Filter
  correlation_filter_enabled: true  # Включим после тестов
  correlation_filter:
    max_correlated_positions: 1   # Максимум 1 позиция в коррелированных парах
    correlation_threshold: 0.7    # Порог высокой корреляции (>0.7)
    block_same_direction_only: true  # Блокировать только одинаковые направления
  
  # PHASE 1: Time-Based Filter
  time_filter_enabled: true  # Включим после тестов
  time_filter:
    trade_asian_session: true       # Торговать Азиатскую сессию (00:00-09:00 UTC)
    trade_european_session: true    # Торговать Европейскую сессию (07:00-16:00 UTC)
    trade_american_session: true    # Торговать Американскую сессию (13:00-22:00 UTC)
    prefer_overlaps: false          # Только пересечения сессий (более строго)
    avoid_low_liquidity_hours: true # Избегать часы низкой ликвидности
    avoid_weekends: true            # Не торговать в выходные
  
  # PHASE 1: Volatility Modes
  # ⚠️ ОТКЛЮЧЕНО: ARM (Adaptive Regime Manager) теперь управляет волатильностью
  volatility_modes_enabled: false  # Заменено на ARM
  volatility_modes:
    low_volatility_threshold: 0.01   # <1% = LOW VOL
    high_volatility_threshold: 0.02  # >2% = HIGH VOL
    # LOW VOLATILITY (узкие стопы, легче вход)
    low_vol_sl_multiplier: 1.5
    low_vol_tp_multiplier: 1.0
    low_vol_score_threshold: 6
    low_vol_position_size_multiplier: 1.2
    # NORMAL (стандартные параметры)
    normal_vol_sl_multiplier: 2.5
    normal_vol_tp_multiplier: 1.5
    normal_vol_score_threshold: 7
    normal_vol_position_size_multiplier: 1.0
    # HIGH VOLATILITY (широкие стопы, строже вход, меньше размер)
    high_vol_sl_multiplier: 3.5
    high_vol_tp_multiplier: 2.5
    high_vol_score_threshold: 8
    high_vol_position_size_multiplier: 0.7
  
  # PHASE 1: Pivot Points
  pivot_points_enabled: true  # Включим после тестов
  pivot_points:
    daily_timeframe: "1D"          # Таймфрейм для расчета
    use_last_n_days: 1             # Использовать последний день
    level_tolerance_percent: 0.003 # Допуск около уровня (0.3%)
    score_bonus_near_level: 1      # Бонус за вход около уровня
    cache_ttl_seconds: 3600        # Кэш 1 час
  
  # PHASE 1: Volume Profile
  volume_profile_enabled: true  # Включим после тестов
  volume_profile:
    lookback_timeframe: "1H"       # Таймфрейм для расчета профиля
    lookback_candles: 100          # Количество свечей
    price_buckets: 50              # Количество ценовых уровней
    value_area_percent: 70.0       # Процент для Value Area (70%)
    score_bonus_in_value_area: 1   # Бонус за вход в Value Area
    score_bonus_near_poc: 1        # Бонус за вход около POC
    poc_tolerance_percent: 0.005   # Допуск около POC (0.5%)
    cache_ttl_seconds: 600         # Кэш 10 минут
  
  indicators:
    sma_fast: 10        # Было: 5 (увеличено для стабильности)
    sma_slow: 30        # Было: 20 (более четкий тренд)
    ema_fast: 8
    ema_slow: 21
    rsi_period: 14
    atr_period: 14
    bollinger_period: 20
    bollinger_std: 2.0
  
  # Entry conditions - СТАНДАРТНЫЕ для скальпинга
  entry:
    min_volatility_atr: 0.0004  # ✅ Было: 0.0005 (торгуем в более спокойном рынке)
    rsi_overbought: 70          # ✅ ИСПРАВЛЕНО: стандартный диапазон RSI
    rsi_oversold: 30            # ✅ ИСПРАВЛЕНО: стандартный диапазон RSI
    volume_threshold: 1.1       # ✅ ИСПРАВЛЕНО: менее строгий фильтр объема
  
  # Exit conditions  
  exit:
    take_profit_atr_multiplier: 1.5  # Было: 2.0 (ближе цель - быстрее фиксация)
    stop_loss_atr_multiplier: 2.5    # Было: 1.5 (больше воздуха - меньше ложных срабатываний)
    max_holding_minutes: 15          # Max time to hold position
    
  # Trade management - УВЕЛИЧИЛИ частоту
  max_trades_per_hour: 15       # ✅ Было: 10 (больше сделок если рынок позволяет)
  cooldown_after_loss_minutes: 4  # ✅ Было: 5 (быстрее возврат)
  
  # PHASE 1: Balance Checker - проверка баланса перед входом
  balance_checker_enabled: true
  balance_checker:
    usdt_reserve_percent: 10.0    # Резерв USDT (10% не используется)
    min_asset_balance_usd: 60.0   # Минимум $60 эквивалента актива для SHORT (OKX requirement)
    min_usdt_balance: 60.0        # Минимум $60 USDT для LONG (OKX requirement)
    log_all_checks: false         # Логировать каждую проверку (для отладки)
  
  # PHASE 1.5: Adaptive Regime Manager - автоматическое переключение режимов
  adaptive_regime_enabled: true
  adaptive_regime:
    # Параметры детекции режимов
    trending_adx_threshold: 25.0        # ADX >25 = сильный тренд
    ranging_adx_threshold: 20.0         # ADX <20 = боковик
    high_volatility_threshold: 0.05     # >5% = высокая волатильность
    low_volatility_threshold: 0.02      # <2% = низкая волатильность
    trend_strength_percent: 2.0         # Отклонение от SMA >2% = тренд
    # Защита от частых переключений
    min_regime_duration_minutes: 15     # Минимум 15 минут в режиме
    required_confirmations: 3           # 3 подтверждения для переключения
    
    # РЕЖИМ 1: TRENDING (агрессивная торговля - берем объемом)
    trending:
      min_score_threshold: 6            # Легкий вход
      max_trades_per_hour: 20           # Много сделок
      position_size_multiplier: 1.2     # Крупнее позиции (+20%)
      tp_atr_multiplier: 2.0            # Дальше цель (тренд продолжится)
      sl_atr_multiplier: 2.0            # Уже стоп (тренд сильный)
      cooldown_after_loss_minutes: 2    # Быстро возвращаемся
      pivot_bonus_multiplier: 1.0       # Стандартные бонусы
      volume_profile_bonus_multiplier: 1.0
    
    # РЕЖИМ 2: RANGING (умеренная торговля - берем качеством)
    ranging:
      min_score_threshold: 8            # Строже отбор
      max_trades_per_hour: 10           # Средне
      position_size_multiplier: 1.0     # Стандартный размер
      tp_atr_multiplier: 1.5            # Ближе цель (диапазон узкий)
      sl_atr_multiplier: 2.5            # Шире стоп (много шума)
      cooldown_after_loss_minutes: 5    # Стандартная пауза
      pivot_bonus_multiplier: 1.5       # Усиление бонусов за уровни!
      volume_profile_bonus_multiplier: 1.5
    
    # РЕЖИМ 3: CHOPPY (консервативная торговля - только проверенное)
    choppy:
      min_score_threshold: 10           # Только лучшие!
      max_trades_per_hour: 4            # Мало сделок
      position_size_multiplier: 0.5     # Половинный размер (защита)
      tp_atr_multiplier: 1.0            # Очень близко (хватай и беги)
      sl_atr_multiplier: 3.5            # Очень широко (хаос)
      cooldown_after_loss_minutes: 15   # Долгая пауза
      pivot_bonus_multiplier: 2.0       # Максимальное усиление!
      volume_profile_bonus_multiplier: 2.0
  
  # Partial Take Profit - многоуровневая фиксация прибыли
  partial_tp_enabled: true
  partial_tp_levels:
    - percent: 50.0           # 50% позиции
      atr_multiplier: 1.5     # На 1.5 ATR
    - percent: 30.0           # 30% позиции
      atr_multiplier: 2.5     # На 2.5 ATR
    - percent: 20.0           # 20% позиции
      atr_multiplier: 4.0     # На 4.0 ATR (пусть летит!)

# Trend Following Strategy
# ⚠️ ОТКЛЮЧЕНО: Конфликтует с Scalping на BTC-USDT
# ARM (Adaptive Regime Manager) теперь управляет режимами автоматически
trend_following:
  enabled: false  # Отключено в пользу ARM
  symbols: ["BTC-USDT"]
  timeframe: "15m"
  indicators:
    sma_fast: 50
    sma_slow: 200
    ema_trend: 100
    rsi_period: 14
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    atr_period: 14
  
  entry:
    min_trend_strength: 0.02  # Price should be 2% above/below MA
    rsi_confirmation: true
    volume_confirmation: true
  
  exit:
    take_profit_percent: 3.0
    stop_loss_percent: 1.5
    trailing_stop_atr_multiplier: 2.0

# Logging
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name} | {message}"
  rotation: "100 MB"
  retention: "30 days"
  
# Notifications
notifications:
  telegram:
    enabled: false
    bot_token: "${TELEGRAM_BOT_TOKEN}"
    chat_id: "${TELEGRAM_CHAT_ID}"
    
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "${EMAIL_USERNAME}"
    password: "${EMAIL_PASSWORD}"
    recipients: ["${EMAIL_RECIPIENT}"]

# Database
database:
  url: "sqlite:///trading_bot.db"
  echo: false

# Monitoring
monitoring:
  prometheus:
    enabled: true
    port: 8000
  
  health_check:
    enabled: true
    port: 8080
    
# Backtesting
backtest:
  start_date: "2023-01-01"
  end_date: "2024-01-01"
  initial_balance: 10000
  commission: 0.001  # 0.1% commission