# Trading Bot Configuration
api:
  okx:
    # Set these in environment variables or .env file
    api_key: "${OKX_API_KEY}"
    api_secret: "${OKX_API_SECRET}"
    passphrase: "${OKX_PASSPHRASE}"
    sandbox: true  # Демо-режим OKX
    
trading:
  symbols: 
    - "BTC-USDT"   # ✅ Bitcoin - лучшая ликвидность
    - "ETH-USDT"   # ✅ Ethereum - вторая по капитализации
  base_currency: "USDT"
  
# Risk Management
risk:
  max_position_size_percent: 5.0  # Max 5% of balance per position
  max_daily_loss_percent: 10.0    # Stop trading if daily loss exceeds 10%
  risk_per_trade_percent: 1.0     # Risk 1% per trade
  max_open_positions: 3           # Maximum concurrent positions

# Scalping Strategy
scalping:
  enabled: true
  symbols: ["BTC-USDT", "ETH-USDT"]  # ✅ Комбо параметры: 2 пары, $70 позиция
  timeframe: "5m"  # 1m не работает в DEMO (статичные данные), используем 5m
  
  # ⚙️ Trading Direction Control
  allow_short_positions: true   # ✅ SHORT разрешены (будут работать после первых LONG)
  allow_long_positions: true    # ✅ LONG разрешены
  
  # PHASE 1: Multi-Timeframe Confirmation (MTF)
  multi_timeframe_enabled: true  # Включим после тестов
  multi_timeframe:
    confirmation_timeframe: "15m"  # Таймфрейм для подтверждения (больше чем основной)
    score_bonus: 2                # Бонус к score при подтверждении
    block_opposite: true          # Блокировать противоположные сигналы
    ema_fast_period: 8            # Период быстрой EMA
    ema_slow_period: 21           # Период медленной EMA
    cache_ttl_seconds: 30         # Кэш свечей (секунды)
  
  # PHASE 1: Correlation Filter
  correlation_filter_enabled: true  # Включим после тестов
  correlation_filter:
    max_correlated_positions: 1   # Максимум 1 позиция в коррелированных парах
    correlation_threshold: 0.7    # Порог высокой корреляции (>0.7)
    block_same_direction_only: true  # Блокировать только одинаковые направления
  
  # PHASE 1: Time-Based Filter
  time_filter_enabled: false  # ❌ ОТКЛЮЧЕНО для теста (крипта 24/7!)
  time_filter:
    trade_asian_session: true       # Торговать Азиатскую сессию (00:00-09:00 UTC)
    trade_european_session: true    # Торговать Европейскую сессию (07:00-16:00 UTC)
    trade_american_session: true    # Торговать Американскую сессию (13:00-22:00 UTC)
    prefer_overlaps: false          # Только пересечения сессий (более строго)
    avoid_low_liquidity_hours: true # Избегать часы низкой ликвидности
    avoid_weekends: true            # Не торговать в выходные
  
  # PHASE 1: Volatility Modes
  # ⚠️ ОТКЛЮЧЕНО: ARM (Adaptive Regime Manager) теперь управляет волатильностью
  volatility_modes_enabled: false  # Заменено на ARM
  volatility_modes:
    low_volatility_threshold: 0.01   # <1% = LOW VOL
    high_volatility_threshold: 0.02  # >2% = HIGH VOL
    # LOW VOLATILITY (узкие стопы, легче вход)
    low_vol_sl_multiplier: 1.5
    low_vol_tp_multiplier: 1.0
    low_vol_score_threshold: 6
    low_vol_position_size_multiplier: 1.2
    # NORMAL (стандартные параметры)
    normal_vol_sl_multiplier: 2.5
    normal_vol_tp_multiplier: 1.5
    normal_vol_score_threshold: 7
    normal_vol_position_size_multiplier: 1.0
    # HIGH VOLATILITY (широкие стопы, строже вход, меньше размер)
    high_vol_sl_multiplier: 3.5
    high_vol_tp_multiplier: 2.5
    high_vol_score_threshold: 8
    high_vol_position_size_multiplier: 0.7
  
  # PHASE 1: Pivot Points
  pivot_points_enabled: true  # Включим после тестов
  pivot_points:
    daily_timeframe: "1D"          # Таймфрейм для расчета
    use_last_n_days: 1             # Использовать последний день
    level_tolerance_percent: 0.003 # Допуск около уровня (0.3%)
    score_bonus_near_level: 1      # Бонус за вход около уровня
    cache_ttl_seconds: 3600        # Кэш 1 час
  
  # PHASE 1: Volume Profile
  volume_profile_enabled: true  # Включим после тестов
  volume_profile:
    lookback_timeframe: "1H"       # Таймфрейм для расчета профиля
    lookback_candles: 100          # Количество свечей
    price_buckets: 50              # Количество ценовых уровней
    value_area_percent: 70.0       # Процент для Value Area (70%)
    score_bonus_in_value_area: 1   # Бонус за вход в Value Area
    score_bonus_near_poc: 1        # Бонус за вход около POC
    poc_tolerance_percent: 0.005   # Допуск около POC (0.5%)
    cache_ttl_seconds: 600         # Кэш 10 минут
  
  indicators:
    sma_fast: 10        # Было: 5 (увеличено для стабильности)
    sma_slow: 30        # Было: 20 (более четкий тренд)
    ema_fast: 8
    ema_slow: 21
    rsi_period: 14
    atr_period: 14
    bollinger_period: 20
    bollinger_std: 2.0
  
  # Entry conditions - СТАНДАРТНЫЕ для скальпинга
  entry:
    min_volatility_atr: 0.0004  # ✅ Было: 0.0005 (торгуем в более спокойном рынке)
    rsi_overbought: 70          # ✅ ИСПРАВЛЕНО: стандартный диапазон RSI
    rsi_oversold: 30            # ✅ ИСПРАВЛЕНО: стандартный диапазон RSI
    volume_threshold: 1.1       # ✅ ИСПРАВЛЕНО: менее строгий фильтр объема
  
  # Exit conditions  
  exit:
    take_profit_atr_multiplier: 1.5  # Было: 2.0 (ближе цель - быстрее фиксация)
    stop_loss_atr_multiplier: 2.5    # Было: 1.5 (больше воздуха - меньше ложных срабатываний)
    max_holding_minutes: 15          # Max time to hold position
    
  # Trade management - УВЕЛИЧИЛИ частоту
    max_trades_per_hour: 15       # ✅ Было: 10 (больше сделок если рынок позволяет)
    cooldown_after_loss_minutes: 4  # ✅ Было: 5 (быстрее возврат)
  
  # PHASE 1: Balance Checker - проверка баланса перед входом
  balance_checker_enabled: true
  balance_checker:
    usdt_reserve_percent: 10.0    # Резерв USDT (10% не используется)
    min_asset_balance_usd: 50.0   # Минимум $50 (оптимально для SOL/AVAX/DOGE)
    min_usdt_balance: 50.0        # Минимум $50 USDT для LONG
    log_all_checks: false         # Логировать каждую проверку (для отладки)
  
  # PHASE 1.5: Adaptive Regime Manager - автоматическое переключение режимов
  adaptive_regime_enabled: true   # ✅ Конфигурация исправлена!
  adaptive_regime:
    # Параметры детекции режимов
    trending_adx_threshold: 20.0        # ADX >20 = тренд (было 25)
    ranging_adx_threshold: 15.0         # ADX <15 = боковик (было 20)
    high_volatility_threshold: 0.03     # >3% = высокая волатильность (было 5%)
    low_volatility_threshold: 0.01      # <1% = низкая волатильность (было 2%)
    trend_strength_percent: 1.0         # Отклонение от SMA >1% = тренд (было 2%)
    # Защита от частых переключений
    min_regime_duration_minutes: 5      # Минимум 5 минут в режиме (было 15)
    required_confirmations: 2           # 2 подтверждения для переключения (было 3)
    
    # РЕЖИМ 1: TRENDING (агрессивная торговля - берем объемом)
    trending:
      # Основные пороги
      min_score_threshold: 6            # Легкий вход (50%)
      max_trades_per_hour: 20           # Много сделок
      position_size_multiplier: 1.2     # Крупнее позиции (+20%)
      tp_atr_multiplier: 1.5            # СКАЛЬП: ~0.2% TP (реалистично с 5сек интервалом)
      sl_atr_multiplier: 1.25           # СКАЛЬП: ~0.15% SL
      max_holding_minutes: 10           # СКАЛЬП: 10 минут максимум
      cooldown_after_loss_minutes: 2    # Быстро возвращаемся
      pivot_bonus_multiplier: 1.5       # Усиленные бонусы (уровни работают в тренде)
      volume_profile_bonus_multiplier: 1.0
    
      # Параметры индикаторов для трендового рынка
      indicators:
        rsi_overbought: 70              # СКАЛЬП: четкие сигналы (не слишком широко)
        rsi_oversold: 30                # СКАЛЬП: четкие сигналы
        volume_threshold: 1.05          # Меньше требования к объему
        sma_fast: 8                     # Быстрее реакция на тренд
        sma_slow: 25                    # Быстрее реакция на тренд
        ema_fast: 8                     # Быстрая EMA для тренда
        ema_slow: 21                    # Медленная EMA для тренда
        atr_period: 14                  # Стандартный период
        min_volatility_atr: 0.0003      # Низкий порог - торгуем слабые тренды
      
      # Параметры модулей для трендового рынка
      modules:
        multi_timeframe:
          block_opposite: false         # Разрешить торговлю против MTF
          score_bonus: 1                # Меньше влияния MTF
          confirmation_timeframe: "30m"  # Долгосрочный взгляд для трендов
        
        correlation_filter:
          correlation_threshold: 0.8    # Менее строгая корреляция
          max_correlated_positions: 3   # Больше коррелированных позиций
          block_same_direction_only: false
        
        time_filter:
          prefer_overlaps: true         # Предпочитать активные сессии
          avoid_low_liquidity_hours: false  # Торговать и в тихие часы
        
        pivot_points:
          level_tolerance_percent: 0.4  # Шире зоны уровней
          score_bonus_near_level: 1     # Стандартный бонус
          use_last_n_days: 3           # Меньше исторических данных
        
        volume_profile:
          score_bonus_in_value_area: 1  # Стандартный бонус
          score_bonus_near_poc: 1       # Стандартный бонус
          poc_tolerance_percent: 0.4    # Шире зона POC
          lookback_candles: 100         # Меньше исторических данных
  
    # РЕЖИМ 2: RANGING (умеренная торговля - берем качеством)
    ranging:
      # Основные пороги
      min_score_threshold: 3            # 🔥 ПОНИЖЕНО: 4→3 (25% - еще больше сигналов!)
      max_trades_per_hour: 10           # Средне
      position_size_multiplier: 1.0     # Стандартный размер
      tp_atr_multiplier: 1.25           # СКАЛЬП: ~0.15% TP (реалистично с 5сек интервалом)
      sl_atr_multiplier: 1.0            # СКАЛЬП: ~0.12% SL
      max_holding_minutes: 5            # СКАЛЬП: 5 минут максимум
      cooldown_after_loss_minutes: 5    # Стандартная пауза
      pivot_bonus_multiplier: 1.5       # Усиление бонусов за уровни!
      volume_profile_bonus_multiplier: 1.5
    
      # Параметры индикаторов для бокового рынка
      indicators:
        rsi_overbought: 70              # Стандартные уровни
        rsi_oversold: 30                # Стандартные уровни
        volume_threshold: 1.1           # Стандартные требования
        sma_fast: 10                    # Стандартные периоды
        sma_slow: 30                    # Стандартные периоды
        ema_fast: 10                    # Средняя EMA для ranging
        ema_slow: 30                    # Средняя EMA для ranging
        atr_period: 14                  # Стандартный период
        min_volatility_atr: 0.0005      # Средний порог - стабильность
      
      # Параметры модулей для бокового рынка
      modules:
        multi_timeframe:
          block_opposite: true          # Блокировать противоположные сигналы
          score_bonus: 2                # Стандартное влияние MTF
          confirmation_timeframe: "15m"  # Таймфрейм для подтверждения
        
        correlation_filter:
          correlation_threshold: 0.7    # Стандартная корреляция
          max_correlated_positions: 2   # Стандартное количество
          block_same_direction_only: true
        
        time_filter:
          prefer_overlaps: true         # Предпочитать пересечения сессий
          avoid_low_liquidity_hours: true  # Избегать тихие часы
        
        pivot_points:
          level_tolerance_percent: 0.25 # Точнее зоны уровней
          score_bonus_near_level: 2     # Больше бонус за уровни
          use_last_n_days: 5           # Стандартные исторические данные
        
        volume_profile:
          score_bonus_in_value_area: 2  # Важность зон значимости
          score_bonus_near_poc: 2       # Важность POC
          poc_tolerance_percent: 0.25   # Точнее зона POC
          lookback_candles: 200         # Стандартные исторические данные
  
    # РЕЖИМ 3: CHOPPY (консервативная торговля - только проверенное)
    choppy:
      # Основные пороги
      min_score_threshold: 5            # 🔥 ИСПРАВЛЕНО: 7→5 (42% - достижимо с бонусами!)
      max_trades_per_hour: 4            # Мало сделок
      position_size_multiplier: 0.6     # Уменьшенный размер (защита)
      tp_atr_multiplier: 1.0            # СКАЛЬП: ~0.12% TP (реалистично с 5сек интервалом)
      sl_atr_multiplier: 0.75           # СКАЛЬП: ~0.09% SL (жесткий стоп)
      max_holding_minutes: 3            # СКАЛЬП: 3 минуты - хватай и беги!
      cooldown_after_loss_minutes: 15   # Долгая пауза
      pivot_bonus_multiplier: 2.0       # Максимальное усиление!
      volume_profile_bonus_multiplier: 2.0
    
      # Параметры индикаторов для хаотичного рынка
      indicators:
        rsi_overbought: 65              # Узкий диапазон - только сильные сигналы
        rsi_oversold: 35                # Консервативные уровни
        volume_threshold: 1.25          # Высокие требования к объему
        sma_fast: 8                     # СКАЛЬП: быстрая реакция (2 мин позиции!)
        sma_slow: 25                    # СКАЛЬП: быстрая реакция
        ema_fast: 8                     # СКАЛЬП: быстрая EMA для 2-мин позиций
        ema_slow: 21                    # СКАЛЬП: быстрая EMA
        atr_period: 14                  # СКАЛЬП: стандартный (не сглаживать)
        min_volatility_atr: 0.0004      # СКАЛЬП: ниже RANGING (больше сигналов)
      
      # Параметры модулей для хаотичного рынка
      modules:
        multi_timeframe:
          block_opposite: false         # 🔥 ИСПРАВЛЕНО: true→false (не блокируем в хаосе!)
          score_bonus: 2                # 🔥 УМЕНЬШЕНО: 3→2 (бонус если подтвердит, но не блокируем)
          confirmation_timeframe: "15m" # СКАЛЬП: быстрый таймфрейм для 2-мин позиций
        
        correlation_filter:
          correlation_threshold: 0.6    # Очень строгая корреляция
          max_correlated_positions: 1   # Только одна коррелированная позиция
          block_same_direction_only: true
        
        time_filter:
          prefer_overlaps: true         # Только пересечения сессий
          avoid_low_liquidity_hours: true  # Строго избегать тихие часы
          avoid_weekends: true          # Избегать выходные
        
        pivot_points:
          level_tolerance_percent: 0.2  # СКАЛЬП: не слишком узко ($225 зона для BTC)
          score_bonus_near_level: 3     # Максимальный бонус за уровни
          use_last_n_days: 5            # СКАЛЬП: средний период (не переобучать)
        
        volume_profile:
          score_bonus_in_value_area: 3  # Максимальная важность зон
          score_bonus_near_poc: 3       # Максимальная важность POC
          poc_tolerance_percent: 0.15   # Очень точная зона POC
          lookback_candles: 300         # Больше исторических данных
  
  # Partial Take Profit - ОТКЛЮЧЕНО для скальпинга (позиции слишком малы)
  partial_tp_enabled: false
  partial_tp_levels:
    - percent: 50.0           # 50% позиции
      atr_multiplier: 1.5     # На 1.5 ATR
    - percent: 30.0           # 30% позиции
      atr_multiplier: 2.5     # На 2.5 ATR
    - percent: 20.0           # 20% позиции
      atr_multiplier: 4.0     # На 4.0 ATR (пусть летит!)

# Trend Following Strategy  
# ⚠️ ОТКЛЮЧЕНО: Конфликтует с Scalping на BTC-USDT
# ARM (Adaptive Regime Manager) теперь управляет режимами автоматически
trend_following:
  enabled: false  # Отключено в пользу ARM
  symbols: ["BTC-USDT"]
  timeframe: "15m"
  indicators:
    sma_fast: 50
    sma_slow: 200
    ema_trend: 100
    rsi_period: 14
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    atr_period: 14
  
  entry:
    min_trend_strength: 0.02  # Price should be 2% above/below MA
    rsi_confirmation: true
    volume_confirmation: true
  
  exit:
    take_profit_percent: 3.0
    stop_loss_percent: 1.5
    trailing_stop_atr_multiplier: 2.0

# Logging
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name} | {message}"
  rotation: "100 MB"
  retention: "30 days"
  
# Notifications
notifications:
  telegram:
    enabled: false
    bot_token: "${TELEGRAM_BOT_TOKEN}"
    chat_id: "${TELEGRAM_CHAT_ID}"
    
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "${EMAIL_USERNAME}"
    password: "${EMAIL_PASSWORD}"
    recipients: ["${EMAIL_RECIPIENT}"]

# Database
database:
  url: "sqlite:///trading_bot.db"
  echo: false

# Monitoring
monitoring:
  prometheus:
    enabled: true
    port: 8000
  
  health_check:
    enabled: true
    port: 8080
    
# Backtesting
backtest:
  start_date: "2023-01-01"
  end_date: "2024-01-01"
  initial_balance: 10000
  commission: 0.001  # 0.1% commission
