# Trading Bot Configuration
api:
  okx:
    # Set these in environment variables or .env file
    api_key: "${OKX_API_KEY}"
    api_secret: "${OKX_API_SECRET}"
    passphrase: "${OKX_PASSPHRASE}"
    sandbox: true  # Демо-режим OKX
    
trading:
  symbols: 
    - "BTC-USDT"
    - "ETH-USDT"
    - "SOL-USDT"
  base_currency: "USDT"
  
# Risk Management - 🛡️ ГАРМОНИЗИРОВАННЫЕ НАСТРОЙКИ
risk:
  max_position_size_percent: 3.0  # Max 3% of balance per position (⬇️ было 5%)
  max_daily_loss_percent: 5.0     # Stop trading if daily loss exceeds 5% (⬇️ было 10%)
  risk_per_trade_percent: 0.5     # Risk 0.5% per trade (⬇️ было 1%)
  max_open_positions: 2           # Maximum concurrent positions (⬇️ было 3)

# Scalping Strategy
scalping:
  enabled: true
  symbols: ["BTC-USDT", "ETH-USDT", "SOL-USDT"]
  timeframe: "1m"
  indicators:
    sma_fast: 5
    sma_slow: 20
    ema_fast: 8
    ema_slow: 21
    rsi_period: 14
    atr_period: 14
    bollinger_period: 20
    bollinger_std: 2.0
  
  # Entry conditions - 🎯 БОЛЕЕ СТРОГИЕ (качество > количество)
  entry:
    min_volatility_atr: 0.0006  # ⬆️ Было: 0.0004 (торгуем только при хорошей волатильности)
    rsi_overbought: 70          # Было: 68 (возврат к классике)
    rsi_oversold: 30            # Было: 32 (возврат к классике)
    volume_threshold: 1.3       # ⬆️ Было: 1.15 (требуем больше объёма)
  
  # Exit conditions - ⚖️ БАЛАНС РИСКА И ПРИБЫЛИ
  exit:
    take_profit_atr_multiplier: 2.0  # ⬆️ Было: 1.5 (дальше цель - больше профит)
    stop_loss_atr_multiplier: 2.0    # ⬇️ Было: 2.5 (ближе стоп - меньше убыток)
    max_holding_minutes: 30          # ⬆️ Было: 15 (даём больше времени развиться тренду)
    
  # Trade management - 🎛️ ОПТИМИЗИРОВАННАЯ ЧАСТОТА
  max_trades_per_hour: 8        # ⬇️ Было: 15 (меньше = качественнее)
  cooldown_after_loss_minutes: 10  # ⬆️ Было: 4 (больше пауза после убытка)

# Trend Following Strategy  
trend_following:
  enabled: true
  symbols: ["BTC-USDT"]
  timeframe: "15m"
  indicators:
    sma_fast: 50
    sma_slow: 200
    ema_trend: 100
    rsi_period: 14
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    atr_period: 14
  
  entry:
    min_trend_strength: 0.02  # Price should be 2% above/below MA
    rsi_confirmation: true
    volume_confirmation: true
  
  exit:
    take_profit_percent: 3.0
    stop_loss_percent: 1.5
    trailing_stop_atr_multiplier: 2.0

# Logging - 📝 ОПТИМИЗАЦИЯ (меньше файлов, проще анализ)
logging:
  level: "INFO"  # ✅ DEBUG только при отладке
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name} | {message}"
  rotation: "20 MB"   # ⬇️ Было: 100 MB (чаще ротация)
  retention: "7 days"  # ⬇️ Было: 30 days (меньше хранение)
  
# Notifications
notifications:
  telegram:
    enabled: false
    bot_token: "${TELEGRAM_BOT_TOKEN}"
    chat_id: "${TELEGRAM_CHAT_ID}"
    
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "${EMAIL_USERNAME}"
    password: "${EMAIL_PASSWORD}"
    recipients: ["${EMAIL_RECIPIENT}"]

# Database
database:
  url: "sqlite:///trading_bot.db"
  echo: false

# Monitoring
monitoring:
  prometheus:
    enabled: true
    port: 8000
  
  health_check:
    enabled: true
    port: 8080
    
# Backtesting
backtest:
  start_date: "2023-01-01"
  end_date: "2024-01-01"
  initial_balance: 10000
  commission: 0.001  # 0.1% commission