from __future__ import annotations

from collections import Counter, defaultdict
from pathlib import Path

PROJECT_ROOT = Path(".")
TESTS_ROOT = PROJECT_ROOT / "tests"
OUTPUT = PROJECT_ROOT / "TESTS_INDEX.md"


def iter_files(root: Path):
    for p in root.rglob("*"):
        if p.is_file():
            yield p


def classify(path: Path) -> str:
    rel = path.relative_to(TESTS_ROOT).as_posix().lower()
    if rel.startswith("unit/"):
        return "unit"
    if rel.startswith("integration/"):
        return "integration"
    if rel.startswith("futures/"):
        return "futures"
    if rel.startswith("smoke/"):
        return "smoke"
    if rel.startswith("main/"):
        return "main_scenarios"
    if rel.startswith("debug/"):
        return "debug"
    if rel.startswith("check/"):
        return "check"
    if rel.startswith("emergency/"):
        return "emergency"
    if rel.startswith("backtest/") or rel.startswith("backtesting/"):
        return "backtesting"
    if rel.startswith("optimization/"):
        return "optimization"
    if rel.startswith("tools/"):
        return "tools"
    if rel.startswith("reports/"):
        return "reports"
    if rel.startswith("artifacts/") or rel.startswith("results/"):
        return "artifacts"
    if rel.startswith("archive/"):
        return "archive"
    return "other"


def main() -> None:
    files = sorted(iter_files(TESTS_ROOT), key=lambda p: p.as_posix().lower())
    by_dir = defaultdict(list)
    ext_counter = Counter()
    class_counter = Counter()

    for p in files:
        rel = p.relative_to(PROJECT_ROOT).as_posix()
        rel_dir = p.parent.relative_to(PROJECT_ROOT).as_posix()
        by_dir[rel_dir].append(rel)
        ext_counter[p.suffix.lower() or "<none>"] += 1
        class_counter[classify(p)] += 1

    lines = [
        "# TESTS INDEX",
        "",
        "Autogenerated full index for tests folder.",
        "",
        f"- Total files: **{len(files)}**",
        "",
        "## Quick entrypoints",
        "- `tests/README.md`",
        "- `tests/TESTS_AUDIT_2026-02-21.md`",
        "- `tests/development/TESTS_STANDARDS.md`",
        "",
        "## Categories",
    ]
    for name, cnt in sorted(class_counter.items()):
        lines.append(f"- `{name}`: {cnt}")

    lines.extend(["", "## File types"])
    for ext, cnt in sorted(ext_counter.items(), key=lambda x: (-x[1], x[0])):
        lines.append(f"- `{ext}`: {cnt}")

    lines.extend(["", "## Full tree index"])
    for directory in sorted(by_dir.keys()):
        lines.append("")
        lines.append(f"### `{directory}` ({len(by_dir[directory])})")
        for rel in by_dir[directory]:
            lines.append(f"- `{rel}`")

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Generated {OUTPUT.as_posix()} with {len(files)} files")


if __name__ == "__main__":
    main()
